/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "request.pb-c.h"
void   fifo_request__init
                     (FifoRequest         *message)
{
  static const FifoRequest init_value = FIFO_REQUEST__INIT;
  *message = init_value;
}
size_t fifo_request__get_packed_size
                     (const FifoRequest *message)
{
  assert(message->base.descriptor == &fifo_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fifo_request__pack
                     (const FifoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fifo_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fifo_request__pack_to_buffer
                     (const FifoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fifo_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FifoRequest *
       fifo_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FifoRequest *)
     protobuf_c_message_unpack (&fifo_request__descriptor,
                                allocator, len, data);
}
void   fifo_request__free_unpacked
                     (FifoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fifo_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fifo_response__init
                     (FifoResponse         *message)
{
  static const FifoResponse init_value = FIFO_RESPONSE__INIT;
  *message = init_value;
}
size_t fifo_response__get_packed_size
                     (const FifoResponse *message)
{
  assert(message->base.descriptor == &fifo_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fifo_response__pack
                     (const FifoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fifo_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fifo_response__pack_to_buffer
                     (const FifoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fifo_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FifoResponse *
       fifo_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FifoResponse *)
     protobuf_c_message_unpack (&fifo_response__descriptor,
                                allocator, len, data);
}
void   fifo_response__free_unpacked
                     (FifoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fifo_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor fifo_request__field_descriptors[2] =
{
  {
    "fifo",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FifoRequest, fifo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FifoRequest, body),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fifo_request__field_indices_by_name[] = {
  1,   /* field[1] = body */
  0,   /* field[0] = fifo */
};
static const ProtobufCIntRange fifo_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fifo_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fifo_request",
  "FifoRequest",
  "FifoRequest",
  "",
  sizeof(FifoRequest),
  2,
  fifo_request__field_descriptors,
  fifo_request__field_indices_by_name,
  1,  fifo_request__number_ranges,
  (ProtobufCMessageInit) fifo_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fifo_response__field_descriptors[1] =
{
  {
    "body",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FifoResponse, body),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fifo_response__field_indices_by_name[] = {
  0,   /* field[0] = body */
};
static const ProtobufCIntRange fifo_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fifo_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fifo_response",
  "FifoResponse",
  "FifoResponse",
  "",
  sizeof(FifoResponse),
  1,
  fifo_response__field_descriptors,
  fifo_response__field_indices_by_name,
  1,  fifo_response__number_ranges,
  (ProtobufCMessageInit) fifo_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
