# objs = hello.o kbd.o command.o display.o \
#         insert.o search.o files.o utils.o
# edit : $(objs)
# 	gcc -o edit $(objs)
# $(objs) : defs.h
# kbd.o command.o files.o : command.h
# display.o insert.o search.o files.o : buffer.h

# clean :
# 	rm edit $(objs)

foo = $(bar)
bar = $(ugh)
ugh = Huh?

all:
	echo $(foo)